version: '3.1'

services:

  db:
    image: postgres
    container_name: coupon-db
    environment:
      - POSTGRES_USER=coupondb
      - POSTGRES_PASSWORD=coupondb
      - POSTGRES_DB=coupondb
    ports:
      - '5434:5432'
  redis:
    image: bitnami/redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    environment:
      REDIS_PASSWORD: redis